consortium_cert = """-----BEGIN CERTIFICATE-----
MIIEYDCCA0igAwIBAgIIW0FOUNCBSHEwDQYJKoZIhvcNAQELBQAwdzEkMCIGA1UE
Awwbcm9vdC5iYWFzLmNvbmZsdXgtY2hhaW4ub3JnMRAwDgYDVQQLDAdpdC1kZXB0
MRYwFAYDVQQKDA1jb25mbHV4LWNoYWluMQswCQYDVQQHDAJTSDELMAkGA1UECAwC
U0gxCzAJBgNVBAYTAkNOMB4XDTIyMDIwODEwMjgzM1oXDTI3MDIwNzEwMjgzM1ow
eDEqMCgGA1UEAwwhY29uc29ydGl1bS5iYWFzLmNvbmZsdXgtY2hhaW4ub3JnMQsw
CQYDVQQLDAJyZDEWMBQGA1UECgwNY29uZmx1eC1jaGFpbjELMAkGA1UEBwwCU0gx
CzAJBgNVBAgMAlNIMQswCQYDVQQGEwJDTjCCASIwDQYJKoZIhvcNAQEBBQADggEP
ADCCAQoCggEBAKfUJq33oEkxXK1Z7iundG44XbAFq3+PBOywsEBeQtK0ydiiHrlN
MmU6oqLKKlqw5B9B0SV2TUdmzpAjU8f59IUzcbdfT5VhBOoe6NPbZH32KBcEQOkz
HMQDPhgMi56iDTIafBFIWG9y2ylF61jIA17rSkvux6XjPbmHCJLcOwd0Cnk1JCcR
Y5FmP/VzCoaO/dnHadqmk0fSwG6gifPaqC8ybnpVVKBb/d8tvmW/dG9wqHmrLybT
VW8eDeGtLg+b5SpartlruT056rGq/NDgl4K+B0M3Ho1UnOlU9WpGKdtiRigOF4w7
mq3802g8T+uoQn6qp7zz43Wp4e8UIllKuIcCAwEAAaOB7jCB6zAPBgNVHRMBAf8E
BTADAQH/MA4GA1UdDwEB/wQEAwIChDCBqAYDVR0jBIGgMIGdgBSfMhXaiPc1Tumv
qEgB8E+rk3mtdqF7pHkwdzEkMCIGA1UEAwwbcm9vdC5iYWFzLmNvbmZsdXgtY2hh
aW4ub3JnMRAwDgYDVQQLDAdpdC1kZXB0MRYwFAYDVQQKDA1jb25mbHV4LWNoYWlu
MQswCQYDVQQHDAJTSDELMAkGA1UECAwCU0gxCzAJBgNVBAYTAkNOgghdgPkyoYJN
+zAdBgNVHQ4EFgQUaIK9SYFvIGj0Vqpb+qvEK/q7Ng4wDQYJKoZIhvcNAQELBQAD
ggEBAAobQEIyueeU+wOglyP73EJ2zgEcqs3wkLJfKVqaxq41Oluf9/XTpe3amuSR
9DBbhxK+2eQlG/uLYj3u8lJvwiufmh8F9cayiFeyVZw6JEiZg1e8Sw+jggHArEFg
8uFPkI54a9QupBg3C0ogT8lTDElBE/GXj9mnKmOdtIIroONo1v9koYNC0gpaPUg2
WV7EZJOMZi34UQVz71XOnyAa2yYiQVkCaHTrjHzYrw/1fZKCEtQBVVIlWuBLfB1Q
1wCzwNXY/sK5c0wwO8Ow0Wvsrda4/CFDcIHcc62TtQAixFIsnSZuOCguRhTukpSX
zZzPQ78IxUpTX7jATtH2+lb0tjk=
-----END CERTIFICATE-----
"""

consortium_nodes = """cfxnode://465d54a08d967abb7714d2a2d9f1c7a50fc318f1a4cf03b1e1009008fbb99b5e1548cbb021c0e2210c6619b607eca73275476112b7a7ecb4bf02a948e6afed29@192.168.1.102:39000,cfxnode://9d34bc2f6a11f3fa0b000d9bf1b2db3bb5c6335cbf5b23de5b598dea839cbdc8e97f79f485c56b5d9734455437488969d3a361dbc9b7408625d615cfbfbbdbff@192.168.1.242:39000,cfxnode://d677514750fb3de6e79cf5a8a78165868deee8c7ef8a2da3af2426518b09229a64e4fae1c8bf2e85937aa13ab668c0af4c565debaf32b155e577bc5f01313db6@192.168.1.21:39000,cfxnode://29cae59ca8d7c50da2f8e5ad07180439a40552541338c4876edf43e41e0174eaee9b3159bc0bffe0f8ce2c4dc4e312471a5f35c56125420a1da021ad17bc3e61@192.168.1.31:39000"""

consortium_nodes_digest = "gfjgodyeUBM5JK4ZMrEb6G0Yd/F0dMg3BNuIHx5EKJoqFy/bv2QOK1cF13NWqHFbf7nN6PMXbbcvyp3Rm96IOHrlS/xDjdPqhwEmS+w/mqc4JdY7idGV6Pbdl8xZDGX0eu//vtjKGFlyb8ljyJNtFkE/wwvWlMSXJPJFOjNKDITKEmf/nBvRBUMivyvYuNteorZXCtN6vw66AMcFSQTz5Hfm9ijE2P9WbpFtknujXnTRTEfaQJjOXiDuK7NN6pqZI1tNoBjTeOvCepqeUoZTKeYjlBs0Y7WseMfUTPEaIp8sjcnhwxU46w0/vG50w/Mi7KW7jkmO9azfgFAspfg6Mg=="

consortium_keypair = "9d34bc2f6a11f3fa0b000d9bf1b2db3bb5c6335cbf5b23de5b598dea839cbdc8e97f79f485c56b5d9734455437488969d3a361dbc9b7408625d615cfbfbbdbff,0fcf00ac10499af6754bf1ae980880e78b6c6a1e81fc7aa7764a0c2676b36a47"

grpc_server_cert = """-----BEGIN CERTIFICATE-----
MIIEfzCCA2egAwIBAgIIUhEActNEQ8AwDQYJKoZIhvcNAQELBQAweDEqMCgGA1UE
AwwhY29uc29ydGl1bS5iYWFzLmNvbmZsdXgtY2hhaW4ub3JnMQswCQYDVQQLDAJy
ZDEWMBQGA1UECgwNY29uZmx1eC1jaGFpbjELMAkGA1UEBwwCU0gxCzAJBgNVBAgM
AlNIMQswCQYDVQQGEwJDTjAeFw0yMjAyMDgxMDI4MzRaFw0yMzAyMDgxMDI4MzRa
MHExIzAhBgNVBAMMGnJwYy5iYWFzLmNvbmZsdXgtY2hhaW4ub3JnMQswCQYDVQQL
DAJyZDEWMBQGA1UECgwNY29uZmx1eC1jaGFpbjELMAkGA1UEBwwCU0gxCzAJBgNV
BAgMAlNIMQswCQYDVQQGEwJDTjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
ggEBAOZ4N16VCXG1gcgCo4dZ0zHIaN7y6NimNJqmebPSPiKRqyHFpmXXC3+Pw8r9
kf4l0wpp8XFVQZGy6Cq8RB4OJ9PYg7c8ZJG6Egm9zg4nINh3pO1SZorc0dWYl2SL
Kl/BJ1VvSdLcbEWp7QsdMA42gOs+ProuHnPK/5Ky9B6P5zsopMd4XQM/K0vlQy1X
DWMQ008r+tlxAvEpv8e8oNJC4/4SV85ES0f88nDmUnKd7sxEo42YOCwFkYnXpVnw
e5qQaU7n0qu2Ey/A1K8i2q0umPfOuVXPaG2K60cuddkLEo3riP3GV0CA0gqSgxih
T3OFdRHJezSg4FLtqeLmwArLsvECAwEAAaOCARIwggEOMA8GA1UdEwEB/wQFMAMB
Af8wDgYDVR0PAQH/BAQDAgKEMIGoBgNVHSMEgaAwgZ2AFGiCvUmBbyBo9FaqW/qr
xCv6uzYOoXukeTB3MSQwIgYDVQQDDBtyb290LmJhYXMuY29uZmx1eC1jaGFpbi5v
cmcxEDAOBgNVBAsMB2l0LWRlcHQxFjAUBgNVBAoMDWNvbmZsdXgtY2hhaW4xCzAJ
BgNVBAcMAlNIMQswCQYDVQQIDAJTSDELMAkGA1UEBhMCQ06CCFtBTlDQgUhxMB0G
A1UdDgQWBBT+cbPcdbNw0DQQfKusuDRi9+fS8jAhBgNVHREEGjAYhwTAqAHyhwTA
qAFmhwTAqAEVhwTAqAEfMA0GCSqGSIb3DQEBCwUAA4IBAQBibYgZ8SFAPQLpr309
s4tpCwZIDCd9lWH6UCVS3MiFhlRqbWZ1ZF33ZvtBfLKa3XNdz3QwVQ5lWq9hzmq2
XlzkEXI0mXd0Sn1oI7ASkvcvnnh3i2VToVsDWAi2To4esaL1u8321h9LP/Pe5fK0
I32CfgjjtAlWAZPtFKFNGvi9H7G7OGglAhFinx0ViGIZ+UUgUQl0d84sucTCchsC
3zGOqzWyq/uwlCQeTGIhrr2knjXZLgzBCRMCNTtf8Xvr6BX1UZYr9Jmk+PiXTpij
FsNvUb/Eu7x37hfcVyGv2/Io+jO+9ZlHgF+P8I76cF0yseX6bbxoCnZY/q/xVCrL
3Cyx
-----END CERTIFICATE-----
"""

grpc_server_key = """-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEA5ng3XpUJcbWByAKjh1nTMcho3vLo2KY0mqZ5s9I+IpGrIcWm
ZdcLf4/Dyv2R/iXTCmnxcVVBkbLoKrxEHg4n09iDtzxkkboSCb3ODicg2Hek7VJm
itzR1ZiXZIsqX8EnVW9J0txsRantCx0wDjaA6z4+ui4ec8r/krL0Ho/nOyikx3hd
Az8rS+VDLVcNYxDTTyv62XEC8Sm/x7yg0kLj/hJXzkRLR/zycOZScp3uzESjjZg4
LAWRidelWfB7mpBpTufSq7YTL8DUryLarS6Y9865Vc9obYrrRy512QsSjeuI/cZX
QIDSCpKDGKFPc4V1Ecl7NKDgUu2p4ubACsuy8QIDAQABAoIBAFWp1m7N97IvtHsK
3AyZqyHka3J/GGQ6tu/KtA7ONTE1MsY9SIGvAkOaRLzFLogoN/61bTxiY5pLxPbp
fmorectIvYCUro7p+f1r8tSY36EGK6PYjmvL8ySw8Ii7H3dy/HNJh8ecDZSBOi34
3d1Sje2id79NGB2TFRbKdGmNtHVsi+AtPaYHalKqjVLyfrmSzoYgM6YigYRmkSOr
hJh2muVaBTrb2BIGumhxdTWOPXR4m5TkNpQAQVli3aotWbk9Jo/8sEJflDv+MI38
tc+MGmCvRd3b01Lvj/KVwiHWbIODS8e6SRx8pgJyYFudl+W4a/b2EhBcZSA/l95Y
ZTMsnOcCgYEA+LFu1l5aaekP5AoPHexjznP1T4m3EWb6ruLCm+1EhQqSeZpFXJRT
C6fM4fwMhSygqvMYh4g6UR09+7LRxpdyjrY5UFhqDdYmQJdzLfjiOrqbU+m28nTt
r7nEd/mQGMnW2fdK2yLeDs41KomixRP1PCZPIdWx+kt0OOhxY7NDR7MCgYEA7T22
saPOIWyI6r4e8pF+wECtjrJL03aar34EEYQs0sDFsMiNw6xN11h9K6NRIfbNtUFI
XqDv64S+M+wqYO6X57XjtaWJ7KsVMytMiFLmRt5lMD57wBGwwTkkumxyELwMaOr6
nevQYMi/k/JH6nt4+qy/c9AU2Pr/Yr0tHqLayMsCgYEA1L38Yfd/AsDz7hDI08FH
s/GwdWUKrSFZ60diUT8McX8UxF+7XDIqRHs8IkmacEY3/2VLo41ezcrlHi7fkzI1
Nm4d42Ru/P0n5fNo/Xe+F51QiN0SuqBaQAv7TOK5aOspF3abm5BdQ28VPhlVm5+y
Fs1yvi/vO31Wo+P8M9zC/k8CgYEAgW9mOc0RLZM1sD1CTT2sVd/z0SLd0+Wlx5GN
TrE6c1HRif4hulxLq+4PfLuCDHHHEdkoTtinjWvDCjkTdgc2waivL++9LG67Bkvd
WZNBJ/E2a/frNINyWDmBHGUGZrLyYluxmG+MJQHh5CoPqpLrEnkli14/wZJPu+NS
tqBLlbkCgYBgRFMoz6DzyxnfF4u0ns5br8KTrhPr8olHjoMz72BI4w98cIToeU8z
gcBrMQuFGoBSbUdZJFlC72Zis1w1fTE83/7t5BBiS3CEfJYciZSBMuoC1h4zrDfi
QZ/CDmjmMKvC5wVg/tu6YflL00mOnn3ai8teH2fyaVTVkIIduJsK5Q==
-----END RSA PRIVATE KEY-----
"""

