consortium_cert = """-----BEGIN CERTIFICATE-----
MIIEYDCCA0igAwIBAgIIW0FOUNCBSHEwDQYJKoZIhvcNAQELBQAwdzEkMCIGA1UE
Awwbcm9vdC5iYWFzLmNvbmZsdXgtY2hhaW4ub3JnMRAwDgYDVQQLDAdpdC1kZXB0
MRYwFAYDVQQKDA1jb25mbHV4LWNoYWluMQswCQYDVQQHDAJTSDELMAkGA1UECAwC
U0gxCzAJBgNVBAYTAkNOMB4XDTIyMDIwODEwMjgzM1oXDTI3MDIwNzEwMjgzM1ow
eDEqMCgGA1UEAwwhY29uc29ydGl1bS5iYWFzLmNvbmZsdXgtY2hhaW4ub3JnMQsw
CQYDVQQLDAJyZDEWMBQGA1UECgwNY29uZmx1eC1jaGFpbjELMAkGA1UEBwwCU0gx
CzAJBgNVBAgMAlNIMQswCQYDVQQGEwJDTjCCASIwDQYJKoZIhvcNAQEBBQADggEP
ADCCAQoCggEBAKfUJq33oEkxXK1Z7iundG44XbAFq3+PBOywsEBeQtK0ydiiHrlN
MmU6oqLKKlqw5B9B0SV2TUdmzpAjU8f59IUzcbdfT5VhBOoe6NPbZH32KBcEQOkz
HMQDPhgMi56iDTIafBFIWG9y2ylF61jIA17rSkvux6XjPbmHCJLcOwd0Cnk1JCcR
Y5FmP/VzCoaO/dnHadqmk0fSwG6gifPaqC8ybnpVVKBb/d8tvmW/dG9wqHmrLybT
VW8eDeGtLg+b5SpartlruT056rGq/NDgl4K+B0M3Ho1UnOlU9WpGKdtiRigOF4w7
mq3802g8T+uoQn6qp7zz43Wp4e8UIllKuIcCAwEAAaOB7jCB6zAPBgNVHRMBAf8E
BTADAQH/MA4GA1UdDwEB/wQEAwIChDCBqAYDVR0jBIGgMIGdgBSfMhXaiPc1Tumv
qEgB8E+rk3mtdqF7pHkwdzEkMCIGA1UEAwwbcm9vdC5iYWFzLmNvbmZsdXgtY2hh
aW4ub3JnMRAwDgYDVQQLDAdpdC1kZXB0MRYwFAYDVQQKDA1jb25mbHV4LWNoYWlu
MQswCQYDVQQHDAJTSDELMAkGA1UECAwCU0gxCzAJBgNVBAYTAkNOgghdgPkyoYJN
+zAdBgNVHQ4EFgQUaIK9SYFvIGj0Vqpb+qvEK/q7Ng4wDQYJKoZIhvcNAQELBQAD
ggEBAAobQEIyueeU+wOglyP73EJ2zgEcqs3wkLJfKVqaxq41Oluf9/XTpe3amuSR
9DBbhxK+2eQlG/uLYj3u8lJvwiufmh8F9cayiFeyVZw6JEiZg1e8Sw+jggHArEFg
8uFPkI54a9QupBg3C0ogT8lTDElBE/GXj9mnKmOdtIIroONo1v9koYNC0gpaPUg2
WV7EZJOMZi34UQVz71XOnyAa2yYiQVkCaHTrjHzYrw/1fZKCEtQBVVIlWuBLfB1Q
1wCzwNXY/sK5c0wwO8Ow0Wvsrda4/CFDcIHcc62TtQAixFIsnSZuOCguRhTukpSX
zZzPQ78IxUpTX7jATtH2+lb0tjk=
-----END CERTIFICATE-----
"""

consortium_nodes = """cfxnode://465d54a08d967abb7714d2a2d9f1c7a50fc318f1a4cf03b1e1009008fbb99b5e1548cbb021c0e2210c6619b607eca73275476112b7a7ecb4bf02a948e6afed29@192.168.1.102:39000,cfxnode://9d34bc2f6a11f3fa0b000d9bf1b2db3bb5c6335cbf5b23de5b598dea839cbdc8e97f79f485c56b5d9734455437488969d3a361dbc9b7408625d615cfbfbbdbff@192.168.1.242:39000,cfxnode://d677514750fb3de6e79cf5a8a78165868deee8c7ef8a2da3af2426518b09229a64e4fae1c8bf2e85937aa13ab668c0af4c565debaf32b155e577bc5f01313db6@192.168.1.21:39000,cfxnode://29cae59ca8d7c50da2f8e5ad07180439a40552541338c4876edf43e41e0174eaee9b3159bc0bffe0f8ce2c4dc4e312471a5f35c56125420a1da021ad17bc3e61@192.168.1.31:39000"""

consortium_nodes_digest = "gfjgodyeUBM5JK4ZMrEb6G0Yd/F0dMg3BNuIHx5EKJoqFy/bv2QOK1cF13NWqHFbf7nN6PMXbbcvyp3Rm96IOHrlS/xDjdPqhwEmS+w/mqc4JdY7idGV6Pbdl8xZDGX0eu//vtjKGFlyb8ljyJNtFkE/wwvWlMSXJPJFOjNKDITKEmf/nBvRBUMivyvYuNteorZXCtN6vw66AMcFSQTz5Hfm9ijE2P9WbpFtknujXnTRTEfaQJjOXiDuK7NN6pqZI1tNoBjTeOvCepqeUoZTKeYjlBs0Y7WseMfUTPEaIp8sjcnhwxU46w0/vG50w/Mi7KW7jkmO9azfgFAspfg6Mg=="

consortium_keypair = "29cae59ca8d7c50da2f8e5ad07180439a40552541338c4876edf43e41e0174eaee9b3159bc0bffe0f8ce2c4dc4e312471a5f35c56125420a1da021ad17bc3e61,a2e9d2183a48c9c456bd3e3251280b99eea738e41a391561a71e93ac3ddfdd26"

grpc_server_cert = """-----BEGIN CERTIFICATE-----
MIIEfzCCA2egAwIBAgIIRKSEaSTXRwMwDQYJKoZIhvcNAQELBQAweDEqMCgGA1UE
AwwhY29uc29ydGl1bS5iYWFzLmNvbmZsdXgtY2hhaW4ub3JnMQswCQYDVQQLDAJy
ZDEWMBQGA1UECgwNY29uZmx1eC1jaGFpbjELMAkGA1UEBwwCU0gxCzAJBgNVBAgM
AlNIMQswCQYDVQQGEwJDTjAeFw0yMjAyMDgxMDI4MzRaFw0yMzAyMDgxMDI4MzRa
MHExIzAhBgNVBAMMGnJwYy5iYWFzLmNvbmZsdXgtY2hhaW4ub3JnMQswCQYDVQQL
DAJyZDEWMBQGA1UECgwNY29uZmx1eC1jaGFpbjELMAkGA1UEBwwCU0gxCzAJBgNV
BAgMAlNIMQswCQYDVQQGEwJDTjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
ggEBALM+PQoPWPnSH7cz5jbnUHsA0/CfTj6f4QN1lYEoAuEMcn0BniENhINf+BAi
Lj3Pudv2plxrzjeRONa7k/QC0P9yJuGurU7zg+8czrEKRonaXBtLTGNOGTi+1DFA
6RyuW6hxrDeC9BddDxQEDfyaTj39AgC2MW4x0jPn17n151Gvc8okdFq9zkf7wAql
EPd74ii97yOEaaBRHduSTTKOBNQ+/Q6ShmspHmO4hbab/nEiQdVSOuS53IO4/uRo
CJI53jhSmxTTYYzop4j3AJvQaWvfgTsI+epdmAlNAe4Vlh0eqcU2QyCuYffKHwiG
qGWPQ8d9E2P5ASKOZ+mX2sa/TgECAwEAAaOCARIwggEOMA8GA1UdEwEB/wQFMAMB
Af8wDgYDVR0PAQH/BAQDAgKEMIGoBgNVHSMEgaAwgZ2AFGiCvUmBbyBo9FaqW/qr
xCv6uzYOoXukeTB3MSQwIgYDVQQDDBtyb290LmJhYXMuY29uZmx1eC1jaGFpbi5v
cmcxEDAOBgNVBAsMB2l0LWRlcHQxFjAUBgNVBAoMDWNvbmZsdXgtY2hhaW4xCzAJ
BgNVBAcMAlNIMQswCQYDVQQIDAJTSDELMAkGA1UEBhMCQ06CCFtBTlDQgUhxMB0G
A1UdDgQWBBT15NpcEvcEOGJRW4/yGMhQ9CneSDAhBgNVHREEGjAYhwTAqAHyhwTA
qAFmhwTAqAEVhwTAqAEfMA0GCSqGSIb3DQEBCwUAA4IBAQAF0rJefoH7ePW9DDJA
KUXH8WIejwJR5WsLwfzVLV0cpTlgPA5+k4Y0dnHllt6BQlXHGH4exIn6b3shd3hC
/6SUnoMwTPjHcJLWf7kz2/Uc6i0sdkXoZc8moOu3c9lfWSf4wgxZGIPG5LwMYrej
wv1ImNGehcuW7q5vmqWZy6tAPOp/DFpxd6p1svzDZVjJmVJnJXFM2HJA8eTl2fcr
TPaq54rqYUsRKJGM+v0lMWk9EbA+LF7milR9gC3emJt6rMGPcJK4XzD5PwtaS2HE
8iGxsTeMOohB3g5I8DNzPr7EuUKfLUbJl0EQ5N0QDRk3AkAGG1HNhCRMMjbuYxpL
q+XR
-----END CERTIFICATE-----
"""

grpc_server_key = """-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAsz49Cg9Y+dIftzPmNudQewDT8J9OPp/hA3WVgSgC4QxyfQGe
IQ2Eg1/4ECIuPc+52/amXGvON5E41ruT9ALQ/3Im4a6tTvOD7xzOsQpGidpcG0tM
Y04ZOL7UMUDpHK5bqHGsN4L0F10PFAQN/JpOPf0CALYxbjHSM+fXufXnUa9zyiR0
Wr3OR/vACqUQ93viKL3vI4RpoFEd25JNMo4E1D79DpKGaykeY7iFtpv+cSJB1VI6
5Lncg7j+5GgIkjneOFKbFNNhjOiniPcAm9Bpa9+BOwj56l2YCU0B7hWWHR6pxTZD
IK5h98ofCIaoZY9Dx30TY/kBIo5n6Zfaxr9OAQIDAQABAoIBABN6QsyILqtmDqF8
O6rxb7TQGhfSneBvA/b55PNGJ2rwbPQB1B7EHudeS0Doj/USUMBzAPC32868wowO
EeWxFSg/DbPWRRm4W1jFXP4Oz2u9PWdPY0eCxfmdPgZ0puhBl676HERjf/YWfBQZ
HTJ7C5/PkbNFWSF/+zc9/TqlWrvM2ZUP28r+DEpWT6MYGmWYFZGh7JCeZw2+7yyv
LoqpnQcC/qlcjYYZ9ImN6YuAXLbV+TlIs6QrKPidyKiHebhESr2juDciXjhS8lbR
JNE2FPDkE4oD5BZC5/lMvHnV8CRh+heyeR0k2KYV9ThVC6c9agPI3WhlZhqE3aI9
xUVi9JkCgYEA+mMiwG95PKHGgYpZRWNmJZk6+Cwk84tForQRDDD81X2Oh+VtAfPA
0C0T7B2ETD5sPPFNwiCPW8jvTjjPLC//p26oe4jaiGAczIwZG6wYa0/PmdyOytA2
gsY/ZiqPJHMwh2fc9FUXTlqs1n2/4fqwoXNgN/HsHz8+RGrLRn8SplkCgYEAt0LW
VpDfKWTe9Yqb0n27K+38ElDZq3wi6GWjw4aXhKm4okLfTvHsjth1pA6iFEfsATAa
BkoI5YF0+dnw93YAkq3qPVoaDzpHhSxTgxXVwpdy9lwvBkGuVEGBH2vIMQv5uBBE
eEvT1ZFBz/Ygbnji8pKg7ZJBtM8d01bGl/fGP+kCgYAOajis9X34VKP1/z4GdaOC
1KCFex0hfEolBNLabdOQgur6veWZsCvQkFfORyC/tvRKSeYdH/zA3v+P9EtREu5X
+FHw0r8qDMZ7rDEh27WIMA8Wn5EE8hnBS6KIwjh9c7g+g2dAFcoCs8uxiYnLe8BB
ez/12JKsddqi27caNuSe+QKBgQCf7FStUFlefydOcToP0ybObCzoMuPxETBJS8FA
dKiu3YlBGEhVVSsRcPYgR6DLQARE+RwM1viyh2l0S+tLmA9h8SETjxhkp4AYSBlM
sHZNDOsG8GUc+Z5O6qbqq50UqBWwuYl2zP08Rzl+aJPes+Ggu7Jx/4sVZRTrA7Pk
lBXOWQKBgA5nCOmoczqlh61DGmys4x1hychzTnccpJWPKDwbznNi9Kg8sUxXLfM4
2AbxOfnO3YPJ/Yw4qNbshXx2J0PsSIEDFh+g7VdU5Azu1QaY6sGKxnXsf0sBIdDb
5Cph8rFnZLuJGJLj5p3cKWUNZOgh49aHA/oiGn7y26Tzx2nqOpAA
-----END RSA PRIVATE KEY-----
"""

