consortium_cert = """-----BEGIN CERTIFICATE-----
MIIEYDCCA0igAwIBAgIIW0FOUNCBSHEwDQYJKoZIhvcNAQELBQAwdzEkMCIGA1UE
Awwbcm9vdC5iYWFzLmNvbmZsdXgtY2hhaW4ub3JnMRAwDgYDVQQLDAdpdC1kZXB0
MRYwFAYDVQQKDA1jb25mbHV4LWNoYWluMQswCQYDVQQHDAJTSDELMAkGA1UECAwC
U0gxCzAJBgNVBAYTAkNOMB4XDTIyMDIwODEwMjgzM1oXDTI3MDIwNzEwMjgzM1ow
eDEqMCgGA1UEAwwhY29uc29ydGl1bS5iYWFzLmNvbmZsdXgtY2hhaW4ub3JnMQsw
CQYDVQQLDAJyZDEWMBQGA1UECgwNY29uZmx1eC1jaGFpbjELMAkGA1UEBwwCU0gx
CzAJBgNVBAgMAlNIMQswCQYDVQQGEwJDTjCCASIwDQYJKoZIhvcNAQEBBQADggEP
ADCCAQoCggEBAKfUJq33oEkxXK1Z7iundG44XbAFq3+PBOywsEBeQtK0ydiiHrlN
MmU6oqLKKlqw5B9B0SV2TUdmzpAjU8f59IUzcbdfT5VhBOoe6NPbZH32KBcEQOkz
HMQDPhgMi56iDTIafBFIWG9y2ylF61jIA17rSkvux6XjPbmHCJLcOwd0Cnk1JCcR
Y5FmP/VzCoaO/dnHadqmk0fSwG6gifPaqC8ybnpVVKBb/d8tvmW/dG9wqHmrLybT
VW8eDeGtLg+b5SpartlruT056rGq/NDgl4K+B0M3Ho1UnOlU9WpGKdtiRigOF4w7
mq3802g8T+uoQn6qp7zz43Wp4e8UIllKuIcCAwEAAaOB7jCB6zAPBgNVHRMBAf8E
BTADAQH/MA4GA1UdDwEB/wQEAwIChDCBqAYDVR0jBIGgMIGdgBSfMhXaiPc1Tumv
qEgB8E+rk3mtdqF7pHkwdzEkMCIGA1UEAwwbcm9vdC5iYWFzLmNvbmZsdXgtY2hh
aW4ub3JnMRAwDgYDVQQLDAdpdC1kZXB0MRYwFAYDVQQKDA1jb25mbHV4LWNoYWlu
MQswCQYDVQQHDAJTSDELMAkGA1UECAwCU0gxCzAJBgNVBAYTAkNOgghdgPkyoYJN
+zAdBgNVHQ4EFgQUaIK9SYFvIGj0Vqpb+qvEK/q7Ng4wDQYJKoZIhvcNAQELBQAD
ggEBAAobQEIyueeU+wOglyP73EJ2zgEcqs3wkLJfKVqaxq41Oluf9/XTpe3amuSR
9DBbhxK+2eQlG/uLYj3u8lJvwiufmh8F9cayiFeyVZw6JEiZg1e8Sw+jggHArEFg
8uFPkI54a9QupBg3C0ogT8lTDElBE/GXj9mnKmOdtIIroONo1v9koYNC0gpaPUg2
WV7EZJOMZi34UQVz71XOnyAa2yYiQVkCaHTrjHzYrw/1fZKCEtQBVVIlWuBLfB1Q
1wCzwNXY/sK5c0wwO8Ow0Wvsrda4/CFDcIHcc62TtQAixFIsnSZuOCguRhTukpSX
zZzPQ78IxUpTX7jATtH2+lb0tjk=
-----END CERTIFICATE-----
"""

consortium_nodes = """cfxnode://465d54a08d967abb7714d2a2d9f1c7a50fc318f1a4cf03b1e1009008fbb99b5e1548cbb021c0e2210c6619b607eca73275476112b7a7ecb4bf02a948e6afed29@192.168.1.102:39000,cfxnode://9d34bc2f6a11f3fa0b000d9bf1b2db3bb5c6335cbf5b23de5b598dea839cbdc8e97f79f485c56b5d9734455437488969d3a361dbc9b7408625d615cfbfbbdbff@192.168.1.242:39000,cfxnode://d677514750fb3de6e79cf5a8a78165868deee8c7ef8a2da3af2426518b09229a64e4fae1c8bf2e85937aa13ab668c0af4c565debaf32b155e577bc5f01313db6@192.168.1.21:39000,cfxnode://29cae59ca8d7c50da2f8e5ad07180439a40552541338c4876edf43e41e0174eaee9b3159bc0bffe0f8ce2c4dc4e312471a5f35c56125420a1da021ad17bc3e61@192.168.1.31:39000"""

consortium_nodes_digest = "gfjgodyeUBM5JK4ZMrEb6G0Yd/F0dMg3BNuIHx5EKJoqFy/bv2QOK1cF13NWqHFbf7nN6PMXbbcvyp3Rm96IOHrlS/xDjdPqhwEmS+w/mqc4JdY7idGV6Pbdl8xZDGX0eu//vtjKGFlyb8ljyJNtFkE/wwvWlMSXJPJFOjNKDITKEmf/nBvRBUMivyvYuNteorZXCtN6vw66AMcFSQTz5Hfm9ijE2P9WbpFtknujXnTRTEfaQJjOXiDuK7NN6pqZI1tNoBjTeOvCepqeUoZTKeYjlBs0Y7WseMfUTPEaIp8sjcnhwxU46w0/vG50w/Mi7KW7jkmO9azfgFAspfg6Mg=="

consortium_keypair = "d677514750fb3de6e79cf5a8a78165868deee8c7ef8a2da3af2426518b09229a64e4fae1c8bf2e85937aa13ab668c0af4c565debaf32b155e577bc5f01313db6,7c6bd6d53b79ef92733427a213d9d9437542bb96072cd146c39dea392dd40fd2"

grpc_server_cert = """-----BEGIN CERTIFICATE-----
MIIEfzCCA2egAwIBAgIICwFkheFgRWwwDQYJKoZIhvcNAQELBQAweDEqMCgGA1UE
AwwhY29uc29ydGl1bS5iYWFzLmNvbmZsdXgtY2hhaW4ub3JnMQswCQYDVQQLDAJy
ZDEWMBQGA1UECgwNY29uZmx1eC1jaGFpbjELMAkGA1UEBwwCU0gxCzAJBgNVBAgM
AlNIMQswCQYDVQQGEwJDTjAeFw0yMjAyMDgxMDI4MzRaFw0yMzAyMDgxMDI4MzRa
MHExIzAhBgNVBAMMGnJwYy5iYWFzLmNvbmZsdXgtY2hhaW4ub3JnMQswCQYDVQQL
DAJyZDEWMBQGA1UECgwNY29uZmx1eC1jaGFpbjELMAkGA1UEBwwCU0gxCzAJBgNV
BAgMAlNIMQswCQYDVQQGEwJDTjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
ggEBALaCeyNPwQ3UuNU9ZBzIBvg1Pq8iSST07hZVzSCPrvoUJ4P8ZYBkSEzl5u3V
kN1LRNAfN52PTTXXVcapNtalBmtA+joRS3JdtIfwPPXgGbBHCUHLlHHCpTPfX9ox
jnkncUpGZqxCSWBDsb2g9bpfU6UvAsaTeh74Od0CFbwHRMtb3SK/9f2O0JN64G07
PZkq4hrPrjlNEhG5mhYcPvvp5LE3gikrvhF9/llM4SnOwsLjX/+yoMiWJvSZdtTw
IkMNpjQSkEiEtfXoITQENSOGWVKm8AkqxIHIRbrlyU90R6NbY3UxbMROw5BDj1qP
40e8GmNKYIXmp4p47y1paa/MqGECAwEAAaOCARIwggEOMA8GA1UdEwEB/wQFMAMB
Af8wDgYDVR0PAQH/BAQDAgKEMIGoBgNVHSMEgaAwgZ2AFGiCvUmBbyBo9FaqW/qr
xCv6uzYOoXukeTB3MSQwIgYDVQQDDBtyb290LmJhYXMuY29uZmx1eC1jaGFpbi5v
cmcxEDAOBgNVBAsMB2l0LWRlcHQxFjAUBgNVBAoMDWNvbmZsdXgtY2hhaW4xCzAJ
BgNVBAcMAlNIMQswCQYDVQQIDAJTSDELMAkGA1UEBhMCQ06CCFtBTlDQgUhxMB0G
A1UdDgQWBBR3eFTp5flLfnw+r7SmKaGa+rTP3DAhBgNVHREEGjAYhwTAqAHyhwTA
qAFmhwTAqAEVhwTAqAEfMA0GCSqGSIb3DQEBCwUAA4IBAQAlcP3pb/UKPte48iZQ
NZZNE1/Pq+ayEFEp+XjLZrE1Gu+t+kdCAjQC/EZBZfeV4YsC/oQqVMFgbf+NJhZQ
OgEzN1qWIjQ+w+SAXUsAaGo+mQm9u5CBXnVbej/Wv/HTMrP4w7jU6k6MVN9955gR
IZBSbnToQrpfIxxn1L0EoLqH2rwuPhsncsZYaSotbKdGHcg13xwyl+H0hcFQV1Vt
Zmian5MADkpgEzQcoBLrssoUlz9jIuzM0vdK2+jyUn0QrPBfTp25fQVGnVmy6CvM
yGerJzXOU+9J3pwA6GR1ByYFRvsCxDwQiT6IHdn1g6uVAi23Hr0tfySHEkw2lclR
tapw
-----END CERTIFICATE-----
"""

grpc_server_key = """-----BEGIN RSA PRIVATE KEY-----
MIIEogIBAAKCAQEAtoJ7I0/BDdS41T1kHMgG+DU+ryJJJPTuFlXNII+u+hQng/xl
gGRITOXm7dWQ3UtE0B83nY9NNddVxqk21qUGa0D6OhFLcl20h/A89eAZsEcJQcuU
ccKlM99f2jGOeSdxSkZmrEJJYEOxvaD1ul9TpS8CxpN6Hvg53QIVvAdEy1vdIr/1
/Y7Qk3rgbTs9mSriGs+uOU0SEbmaFhw+++nksTeCKSu+EX3+WUzhKc7CwuNf/7Kg
yJYm9Jl21PAiQw2mNBKQSIS19eghNAQ1I4ZZUqbwCSrEgchFuuXJT3RHo1tjdTFs
xE7DkEOPWo/jR7waY0pgheaninjvLWlpr8yoYQIDAQABAoIBAARyxkQ/WGtlOWDw
aFY5n36dSt0NOAjcp8jLZCK+gMlxbEADsuBB9XeLGRWH+YIkyHldgOssGfHReQKk
x0B8nMUohA7OMwtnVngTnFNCeELRPOvtta1PBQx4VdVnRL+OBSVGJXCOdCwSk1B9
vc6CTjtD+8h98cWTZ5LkBxZGW7RMgw6BuZr7Z7fHUSABWlmgNAosaBM5AmuW/Gle
8BLzt6FoPjyUn/Hcc+wGZhwvXLeY9+UAthFxp/vgLVBcb7q1IlGpkQODypGDAeG0
AxgITiTHrTXNtGnGSX6ML2WYIJuwTiiIv1F37O2xb6R2HL2K7cbBPxVaaDiBoCZb
3Kv2nIECgYEA9VCXkfept9qe4E8sELhCL1k1cowlVvexHfeHoRzjlVgMlfWwbF/1
giSOT7t9d+XJRoc2AY64ZBGRVMHs5CJfaKzy7wI4LtvixOnMKmjxARNtXGNnohzN
x55MExJQQYTZrB2MfIj0qofHlBjXND9iAgGkal2UWIFCeIYeY91sleECgYEAvnWS
8dXX7Da838wWMzo9He8U4cgOa8TkTK8BICpF4JWiHhZOMfVDEIu8zGzqJuAY5M2G
rBzTwE61tLd0ou/dz2Cl48MROJFaF94dz5LRiVW3TAq0FGZHUniBGZL0TWMMoZth
wB9YsSL9bsUYATMBc7f7o8E4zLA9WEzzgKdVYoECgYBOpbbiSkd0NTfobBmRhrFZ
Yr1a6wlxl1mGZPxrr8pa7+6hCTK1nBIm1jd14oM4NEhSPzkWSL5e/q7cQIwFG+wA
sCn2bHy8sSxDuz0Ef758fND75Lat55Qlol97YcyvJLtwjcyjhHkETyGyHkCodIWk
ZQhkPXo44cAAyebmV2/foQKBgC93Q9jrb3WaKrYnubyongSwyeZ/IkDvf+owjzpB
7spK4G1ZJ8HBmyYrfTEBT9XCcdHL+u03/fnmY9iXBAV7fC8rqgw6WDdd2jMqkwlh
UMFGUHkuDbUrzEicaahC/ImwzrwT6mekKEl1K+4IRrQ9zvXU+2zTQeGZZqB0BRei
HGCBAoGAUSQdm06sEXROxcGp0yvLF7e+Y/4bYNGw7IJfe/VDor5biM9GngMCD60i
Q7uhAtCC/Di6BnmJBQwBvQAA8TIHWQ/BcSOmniV3V6h6qVRKS6jmpLcz7L19imup
2Eq9nioTsbH8H1Z5C8hfEjq6LWe9PF43SRW2gqRe3QipjUzfris=
-----END RSA PRIVATE KEY-----
"""

