consortium_cert = """-----BEGIN CERTIFICATE-----
MIIEYDCCA0igAwIBAgIIW0FOUNCBSHEwDQYJKoZIhvcNAQELBQAwdzEkMCIGA1UE
Awwbcm9vdC5iYWFzLmNvbmZsdXgtY2hhaW4ub3JnMRAwDgYDVQQLDAdpdC1kZXB0
MRYwFAYDVQQKDA1jb25mbHV4LWNoYWluMQswCQYDVQQHDAJTSDELMAkGA1UECAwC
U0gxCzAJBgNVBAYTAkNOMB4XDTIyMDIwODEwMjgzM1oXDTI3MDIwNzEwMjgzM1ow
eDEqMCgGA1UEAwwhY29uc29ydGl1bS5iYWFzLmNvbmZsdXgtY2hhaW4ub3JnMQsw
CQYDVQQLDAJyZDEWMBQGA1UECgwNY29uZmx1eC1jaGFpbjELMAkGA1UEBwwCU0gx
CzAJBgNVBAgMAlNIMQswCQYDVQQGEwJDTjCCASIwDQYJKoZIhvcNAQEBBQADggEP
ADCCAQoCggEBAKfUJq33oEkxXK1Z7iundG44XbAFq3+PBOywsEBeQtK0ydiiHrlN
MmU6oqLKKlqw5B9B0SV2TUdmzpAjU8f59IUzcbdfT5VhBOoe6NPbZH32KBcEQOkz
HMQDPhgMi56iDTIafBFIWG9y2ylF61jIA17rSkvux6XjPbmHCJLcOwd0Cnk1JCcR
Y5FmP/VzCoaO/dnHadqmk0fSwG6gifPaqC8ybnpVVKBb/d8tvmW/dG9wqHmrLybT
VW8eDeGtLg+b5SpartlruT056rGq/NDgl4K+B0M3Ho1UnOlU9WpGKdtiRigOF4w7
mq3802g8T+uoQn6qp7zz43Wp4e8UIllKuIcCAwEAAaOB7jCB6zAPBgNVHRMBAf8E
BTADAQH/MA4GA1UdDwEB/wQEAwIChDCBqAYDVR0jBIGgMIGdgBSfMhXaiPc1Tumv
qEgB8E+rk3mtdqF7pHkwdzEkMCIGA1UEAwwbcm9vdC5iYWFzLmNvbmZsdXgtY2hh
aW4ub3JnMRAwDgYDVQQLDAdpdC1kZXB0MRYwFAYDVQQKDA1jb25mbHV4LWNoYWlu
MQswCQYDVQQHDAJTSDELMAkGA1UECAwCU0gxCzAJBgNVBAYTAkNOgghdgPkyoYJN
+zAdBgNVHQ4EFgQUaIK9SYFvIGj0Vqpb+qvEK/q7Ng4wDQYJKoZIhvcNAQELBQAD
ggEBAAobQEIyueeU+wOglyP73EJ2zgEcqs3wkLJfKVqaxq41Oluf9/XTpe3amuSR
9DBbhxK+2eQlG/uLYj3u8lJvwiufmh8F9cayiFeyVZw6JEiZg1e8Sw+jggHArEFg
8uFPkI54a9QupBg3C0ogT8lTDElBE/GXj9mnKmOdtIIroONo1v9koYNC0gpaPUg2
WV7EZJOMZi34UQVz71XOnyAa2yYiQVkCaHTrjHzYrw/1fZKCEtQBVVIlWuBLfB1Q
1wCzwNXY/sK5c0wwO8Ow0Wvsrda4/CFDcIHcc62TtQAixFIsnSZuOCguRhTukpSX
zZzPQ78IxUpTX7jATtH2+lb0tjk=
-----END CERTIFICATE-----
"""

consortium_nodes = """cfxnode://465d54a08d967abb7714d2a2d9f1c7a50fc318f1a4cf03b1e1009008fbb99b5e1548cbb021c0e2210c6619b607eca73275476112b7a7ecb4bf02a948e6afed29@192.168.1.102:39000,cfxnode://9d34bc2f6a11f3fa0b000d9bf1b2db3bb5c6335cbf5b23de5b598dea839cbdc8e97f79f485c56b5d9734455437488969d3a361dbc9b7408625d615cfbfbbdbff@192.168.1.242:39000,cfxnode://d677514750fb3de6e79cf5a8a78165868deee8c7ef8a2da3af2426518b09229a64e4fae1c8bf2e85937aa13ab668c0af4c565debaf32b155e577bc5f01313db6@192.168.1.21:39000,cfxnode://29cae59ca8d7c50da2f8e5ad07180439a40552541338c4876edf43e41e0174eaee9b3159bc0bffe0f8ce2c4dc4e312471a5f35c56125420a1da021ad17bc3e61@192.168.1.31:39000"""

consortium_nodes_digest = "gfjgodyeUBM5JK4ZMrEb6G0Yd/F0dMg3BNuIHx5EKJoqFy/bv2QOK1cF13NWqHFbf7nN6PMXbbcvyp3Rm96IOHrlS/xDjdPqhwEmS+w/mqc4JdY7idGV6Pbdl8xZDGX0eu//vtjKGFlyb8ljyJNtFkE/wwvWlMSXJPJFOjNKDITKEmf/nBvRBUMivyvYuNteorZXCtN6vw66AMcFSQTz5Hfm9ijE2P9WbpFtknujXnTRTEfaQJjOXiDuK7NN6pqZI1tNoBjTeOvCepqeUoZTKeYjlBs0Y7WseMfUTPEaIp8sjcnhwxU46w0/vG50w/Mi7KW7jkmO9azfgFAspfg6Mg=="

consortium_keypair = "465d54a08d967abb7714d2a2d9f1c7a50fc318f1a4cf03b1e1009008fbb99b5e1548cbb021c0e2210c6619b607eca73275476112b7a7ecb4bf02a948e6afed29,2610f7e891e27aeb9aca04662a4dd845c40a75d14ba44d42fbc70c731cdf918a"

grpc_server_cert = """-----BEGIN CERTIFICATE-----
MIIEfzCCA2egAwIBAgIIZeLZRNesSnIwDQYJKoZIhvcNAQELBQAweDEqMCgGA1UE
AwwhY29uc29ydGl1bS5iYWFzLmNvbmZsdXgtY2hhaW4ub3JnMQswCQYDVQQLDAJy
ZDEWMBQGA1UECgwNY29uZmx1eC1jaGFpbjELMAkGA1UEBwwCU0gxCzAJBgNVBAgM
AlNIMQswCQYDVQQGEwJDTjAeFw0yMjAyMDgxMDI4MzNaFw0yMzAyMDgxMDI4MzNa
MHExIzAhBgNVBAMMGnJwYy5iYWFzLmNvbmZsdXgtY2hhaW4ub3JnMQswCQYDVQQL
DAJyZDEWMBQGA1UECgwNY29uZmx1eC1jaGFpbjELMAkGA1UEBwwCU0gxCzAJBgNV
BAgMAlNIMQswCQYDVQQGEwJDTjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
ggEBALqBRGhWUU8iL4rYRBjL4kbKE5gGhsMEUX8zPLzn2KZOcrVklDLQHxlGwNG4
HijCOrp2juM/xIsiBYrpuFGTf6Iu6Q64mVks3BiXZhBttvQIvSX1nXTCrBWM/WGN
7WnCPH/h8iu+hyEJwAVfI/2iWx2SJjaCbtnBDGkgklufscFg9Rp32LZK5Uh3zgFU
h6KdhvDhRFdvlHO47sKlv5yKf3QkFInxKjo+DKf+/Rw2gurYh1Um9D0krRMsxR5U
voPnrSIajzLpDTcw3/GzMVM3bfA3LjSBl7iKRbSATxIfRu/K+sB4n92S58/Chf7S
UKU/7BblXQFKwQFDiKTx5kVauh0CAwEAAaOCARIwggEOMA8GA1UdEwEB/wQFMAMB
Af8wDgYDVR0PAQH/BAQDAgKEMIGoBgNVHSMEgaAwgZ2AFGiCvUmBbyBo9FaqW/qr
xCv6uzYOoXukeTB3MSQwIgYDVQQDDBtyb290LmJhYXMuY29uZmx1eC1jaGFpbi5v
cmcxEDAOBgNVBAsMB2l0LWRlcHQxFjAUBgNVBAoMDWNvbmZsdXgtY2hhaW4xCzAJ
BgNVBAcMAlNIMQswCQYDVQQIDAJTSDELMAkGA1UEBhMCQ06CCFtBTlDQgUhxMB0G
A1UdDgQWBBQt7GX4jo34UYkGB//+cWRANacwOzAhBgNVHREEGjAYhwTAqAHyhwTA
qAFmhwTAqAEVhwTAqAEfMA0GCSqGSIb3DQEBCwUAA4IBAQBx4kvyHK2N9oGgitLZ
Bt+DOuql2YelsIc0VtUKtRFqSX5viQ2HOYEnzvaNuKa6A1Uf2zJRuaPxeHf8xxAO
Z7FRxSwyZiqXCmZwzUZed3vNXedpqeQa2sDksvA1boIRsA5Zy+lAizrmXA0t5EoN
rZMq/rtRadd7NuRqv+3ZAJm4lp9B1TduKPaj82j5Lk0Jnp+oD+CzX6PjI58LyzTr
sG5apWFf6BxiWSWENhzHbI3PRJoL0ll73hUVputDetKk7kCXhHfm7JtXpTeOkht6
MjjPxh8chx34z9LfgI5W9ncb9FNi4k2dWLkVq6UoJSGEtn0E4sfDwyiLcN7quPH8
eygU
-----END CERTIFICATE-----
"""

grpc_server_key = """-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAuoFEaFZRTyIvithEGMviRsoTmAaGwwRRfzM8vOfYpk5ytWSU
MtAfGUbA0bgeKMI6unaO4z/EiyIFium4UZN/oi7pDriZWSzcGJdmEG229Ai9JfWd
dMKsFYz9YY3tacI8f+HyK76HIQnABV8j/aJbHZImNoJu2cEMaSCSW5+xwWD1GnfY
tkrlSHfOAVSHop2G8OFEV2+Uc7juwqW/nIp/dCQUifEqOj4Mp/79HDaC6tiHVSb0
PSStEyzFHlS+g+etIhqPMukNNzDf8bMxUzdt8DcuNIGXuIpFtIBPEh9G78r6wHif
3ZLnz8KF/tJQpT/sFuVdAUrBAUOIpPHmRVq6HQIDAQABAoIBAFA7RdNgtq/FNBCV
wo2sP9ZWHiG7RQPl+q0uvIVDc7bvbndMIljNoWM9Rbuyaf78t0j5sbRe/U0hQKMm
si0dt71sUsQLc6SiILjPgI+2swq+K6iFxcux51eKBIKQDL7/WQlmiMh6uSTkTd/B
svjsfCf3dErkx40TeCRNZ8jUpSJbuGazQ4NzALGJg186P0zO8c3kff2OX5D7HySt
sm3YqLEDTIIlcbzzeVKESMSXnadEy9/adlq25HTwrBP+eGeuemty2jzKguWZQNzf
VhLEeTtdU7HOKCBIYrWKUVC/jw0h0dGMcGWW5YL9AO18JEn0FvyKjOI5JO3RN3NQ
AG9ziB0CgYEA3/lFJihck8sEk4rFwcFBJg/prRqnX6ueJ8UCmHvtczjTxS7EeM8B
iLfLeGu5l/F41SPEFBRyK0Jusu4KMWc1b2D+P08EpWTptXgXnrMP2aGkopxI8GsU
oT1b+gwi9HCn9KKcM2zsjuM6qCYgFW2e2vYk945cMeKUxhE3XLLI+PcCgYEA1Sxs
nlp6Oc3FtIy3jobIb+h5Ta/TZFdEVilCp+YZc59jLuGNzGkzUtwJnDxUZkRdGQoJ
0tPZWdYk4K+gvx/1BpL/nwvPtJNunZD4LH+3BTQP44bX0CaVD2wsNxElfCQ8RHoB
WC6D+kW0D568edV+yhiqTNWbXUBZ2Rm0M5+p1IsCgYEAr4pqJPb7YCZ9Rro8Npil
3BQavL6oMfaLNXZWi3aN64G9kM0P1fPAqwwKYC5mPu1WHA81Ldu8g6VEp96jhIb0
vX/SpYHkDVFjTwR51rtXD+Z956kADdaPS7SQsxDyEI1/ReBw9mlHmtIDdiizerf5
CnpjDNe58Ks6mWaC8pd5po8CgYBg69rSwKZTw7gBF/2ZArT9FICajreZJog+eHIC
7n5h8HTi6tBSwP4BzWNdMpzZBnohmUvQHFv1GYUY1yFJ5Ji+DXXFdVRRcLrZTwFX
EhY/emVC+JsE25XoNjGAM/6MC9mO9L3JvxRoZOqyM2TUK/qCnmZHmtMRueFf8Oza
j9xicwKBgQDTtnJhOQc3TJGgWibhUwsHV7ZFrvq+rsMzGz9t2t9O9ucTkuFh5EaV
1a1YuPm76mKbsT6bHPrQj0FWS3IISkvBonZocmXctg1AK6VbxZLvLEhst5Zi26ll
LqcBxZVMelrG4kTi0XeoGySyq48eHbBRRjcw9w8YgX32cGYVqZBQWQ==
-----END RSA PRIVATE KEY-----
"""

